services:
  letsduckinggameapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - HANGFIRE_CONNECTION=${HANGFIRE_CONNECTION}
    ports:
      - "${PORT:-5000}:8080"
