[phases.setup]
nixPkgs = ["dotnet-sdk_8", "nodejs_20", "yarn"]

[phases.build]
cacheDirectories = ["/root/.nuget/packages", "/app/LetsDuckingGame.Client/node_modules"]
cmds = [
  "cd LetsDuckingGame.Client && yarn install && yarn build",
  "dotnet publish -c Release -o out"
]

[start]
cmd = "dotnet out/LetsDuckingGame.Server.dll"

[variables]
PORT = "5000"
