[phases.setup]
nixPkgs = ["dotnet-sdk_8", "nodejs_20"]

[phases.build]
cacheDirectories = ["/root/.nuget/packages", "/app/letsduckinggame.client/node_modules"]
cmds = [
  "cd letsduckinggame.client && npm install && npm build",
  "dotnet publish -c Release -o out"
]

[start]
cmd = "dotnet out/LetsDuckingGame.Server.dll"

[variables]
PORT = "5000"
